const Nightmare = require('nightmare');
const nightmare = Nightmare({ show: true });

const loginUrl = 'https://cpcdi.pt/Account/Login';
const familyUrl = (family) => `https://cpcdi.pt/Produtos/ListagemProdutos?familia=${family}`;

const authData = {
  clientCode: 38406,
  user: 'shopify',
  password: 'segredo'
};

nightmare
  .goto(loginUrl)
  .type('#CodCliente', authData.clientCode)
  .type('#UserName', authData.user)
  .type('#Password', authData.password)
  .click('button[type=submit]')
  .wait(1500);


nightmare
  .goto(familyUrl('Acess%2BPoint')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Adaptadores_e_Cabos')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Caixas')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Camaras_Fotograficas_Acessorios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Camaras_Fotograficas_Digitais')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Camaras_Vídeo')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Camaras_Vídeo_Acessorios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Cartões%2BPresente')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Colunas_de_Som')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Conectividade')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Consolas_Acessorios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Consolas_de_Jogos')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Consumiveis_de_Gravacao')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Discos_Acessórios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Discos_Externos')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Discos_HDD')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Discos_SSD')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Drives_Ópticas')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Drones')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Drones_Acessorios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Equipamentos_GPS')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Equipamentos_GPS_Acessórios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Gaming_PC_Acessórios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('HealthCare')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Home_Cinema')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Home_Solutions')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Impressoras_3D')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Impressoras_3D_Consumiveis')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Impressoras_Fotograficas')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Impressoras_Jacto_de_Tinta_A4')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Impressoras_Jacto_Tinta_Consumiveis')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Impressoras_Jacto_Tinta_Papeis')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Impressoras_Laser_Consumiveis')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Impressoras_Laser_Cores_A4')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Impressoras_Laser_Mono_A4')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Jogos')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Memorias_Cartoes')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Memorias_PCs')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Memorias_Portateis')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Memorias_USB')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Monitores_TFT')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Motherboards_Pcs')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Multimedia')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('PCs')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('PCs_Acessórios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Placas_Graficas')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Portateis')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Portateis_Acessorios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Power_Banks')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Processadores')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Ratos_para_PCs')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Ratos_para_Portateis')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Redes_Powerline')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Redes_Routers')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Redes_Switch')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Redes_Wireless')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Relógios_Desportivos')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Relógios_Desportivos_Acessórios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Sistemas_Audio')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('SmartBands')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('SmartBands_Acessórios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Smartphones')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('SmartPhones_Acessorios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('SmartWatch')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('SmartWatch_Acessorios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('SW_OFFICE')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('SW_Sistemas_Operativos')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Tablets')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Tablets_Acessórios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Teclados')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Teclados_e_Ratos')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Televisores')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Televisores_Acessorios')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Videoprojectores')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .goto(familyUrl('Videovigilância')).wait('#mostrarEm').select('#mostrarEm', '3').wait(500).click('#botaoexportar').wait(1000)
  .end()
  .then(console.log)
  .catch(console.error)
;
